"""create table simples

Revision ID: 74bcfdc9d13e
Revises: b30001b0996f
Create Date: 2026-02-09 17:58:24.444809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74bcfdc9d13e'
down_revision: Union[str, Sequence[str], None] = 'b30001b0996f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simples',
    sa.Column('cnpj_basico', sa.String(length=10), nullable=False),
    sa.Column('opcao_simples', sa.String(length=1), nullable=False),
    sa.Column('data_opcao_simples', sa.Date(), nullable=True),
    sa.Column('data_exclusao_simples', sa.Date(), nullable=True),
    sa.Column('opcao_mei', sa.String(length=1), nullable=False),
    sa.Column('data_opcao_mei', sa.Date(), nullable=True),
    sa.Column('data_exclusao_mei', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cnpj_basico'], ['empresas.cnpj_basico'], ),
    sa.PrimaryKeyConstraint('cnpj_basico')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simples')
    # ### end Alembic commands ###
