"""create table empresas

Revision ID: 785c118896c7
Revises: cf895cd43dc1
Create Date: 2026-02-08 19:36:23.398348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785c118896c7'
down_revision: Union[str, Sequence[str], None] = 'cf895cd43dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('cnpj_basico', sa.String(length=10), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('natureza_juridica', sa.String(length=7), nullable=False),
    sa.Column('qualificacao_responsavel', sa.String(length=7), nullable=False),
    sa.Column('capital_social', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('porte_empresa', sa.String(length=2), nullable=False),
    sa.Column('ente_federativo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['natureza_juridica'], ['naturezas.codigo'], ),
    sa.ForeignKeyConstraint(['qualificacao_responsavel'], ['qualificacoes.codigo'], ),
    sa.PrimaryKeyConstraint('cnpj_basico')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresas')
    # ### end Alembic commands ###
