"""alter table estabelecimentos foreign_key

Revision ID: 84ef9985c0a3
Revises: 74bcfdc9d13e
Create Date: 2026-02-09 18:37:19.604251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ef9985c0a3'
down_revision: Union[str, Sequence[str], None] = '74bcfdc9d13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'estabelecimentos', 'empresas', ['cnpj_basico'], ['cnpj_basico'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estabelecimentos', type_='foreignkey')
    # ### end Alembic commands ###
