"""create table municipios

Revision ID: 898f5c15b2c6
Revises: fe5eb4665640
Create Date: 2026-02-07 21:20:18.074057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898f5c15b2c6'
down_revision: Union[str, Sequence[str], None] = 'fe5eb4665640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('municipios')
    # ### end Alembic commands ###
