"""create table motivos

Revision ID: abfe1b6195ae
Revises: 785c118896c7
Create Date: 2026-02-09 13:23:03.618193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfe1b6195ae'
down_revision: Union[str, Sequence[str], None] = '785c118896c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motivos',
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motivos')
    # ### end Alembic commands ###
