"""create table qualificacoes

Revision ID: aefbc11769ea
Revises: 898f5c15b2c6
Create Date: 2026-02-07 21:31:16.966956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefbc11769ea'
down_revision: Union[str, Sequence[str], None] = '898f5c15b2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualificacoes',
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualificacoes')
    # ### end Alembic commands ###
