"""create table estabelecimentos

Revision ID: b30001b0996f
Revises: abfe1b6195ae
Create Date: 2026-02-09 14:51:16.891886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30001b0996f'
down_revision: Union[str, Sequence[str], None] = 'abfe1b6195ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estabelecimentos',
    sa.Column('cnpj_basico', sa.String(length=10), nullable=False),
    sa.Column('cnpj_ordem', sa.String(length=4), nullable=False),
    sa.Column('cnpj_dv', sa.String(length=2), nullable=False),
    sa.Column('identificador_matriz_filial', sa.String(length=1), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('situacao_cadastral', sa.String(length=2), nullable=False),
    sa.Column('data_situacao_cadastral', sa.Date(), nullable=False),
    sa.Column('motivo_situacao_cadastral', sa.String(length=7), nullable=False),
    sa.Column('nome_cidade_exterior', sa.String(), nullable=True),
    sa.Column('pais', sa.String(length=7), nullable=True),
    sa.Column('data_inicio_atividade', sa.Date(), nullable=True),
    sa.Column('cnae_fiscal_principal', sa.String(length=7), nullable=False),
    sa.Column('cnae_fiscal_secundaria', sa.String(), nullable=True),
    sa.Column('tipo_logradouro', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('municipio', sa.String(length=7), nullable=False),
    sa.Column('ddd1', sa.String(length=2), nullable=True),
    sa.Column('telefone1', sa.String(), nullable=True),
    sa.Column('ddd2', sa.String(length=2), nullable=True),
    sa.Column('telefone2', sa.String(), nullable=True),
    sa.Column('ddd_fax', sa.String(length=2), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('correio_eletronico', sa.String(), nullable=True),
    sa.Column('situacao_especial', sa.String(), nullable=True),
    sa.Column('data_situacao_especial', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cnae_fiscal_principal'], ['cnaes.codigo'], ),
    sa.ForeignKeyConstraint(['motivo_situacao_cadastral'], ['motivos.codigo'], ),
    sa.ForeignKeyConstraint(['municipio'], ['municipios.codigo'], ),
    sa.ForeignKeyConstraint(['pais'], ['paises.codigo'], ),
    sa.PrimaryKeyConstraint('cnpj_basico', 'cnpj_ordem', 'cnpj_dv')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estabelecimentos')
    # ### end Alembic commands ###
