"""create table naturezas

Revision ID: b7eefe5b3e0a
Revises: aefbc11769ea
Create Date: 2026-02-08 00:48:27.553915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7eefe5b3e0a'
down_revision: Union[str, Sequence[str], None] = 'aefbc11769ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naturezas',
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('naturezas')
    # ### end Alembic commands ###
