"""create table cnaes

Revision ID: cf895cd43dc1
Revises: b7eefe5b3e0a
Create Date: 2026-02-08 01:00:35.476441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf895cd43dc1'
down_revision: Union[str, Sequence[str], None] = 'b7eefe5b3e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnaes',
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cnaes')
    # ### end Alembic commands ###
